import Head from 'next/head'
import Image from 'next/image'
import Intro from '../components/intro'
import styles from '../styles/Home.module.css'

export default function Home() {
    return ( <
        div className = { styles.container } >
        <
        Head >
        <
        title > Create Next App < /title> <
        meta name = "description"
        content = "Generated by create next app" / >
        <
        /Head> <
        Intro / >
        <
        /div>
    )
}